name: CI Pipeline

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      # 🔥 RODA TESTES APENAS UMA VEZ
      - name: Run Tests with Coverage
        run: npm run coverage

      - name: Generate Mochawesome Report (reuse)
        run: mocha --reporter mochawesome

      - name: Generate JUnit Report (reuse)
        run: mocha --reporter mocha-junit-reporter --reporter-options mochaFile=reports/test-results.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports
